# 2012-04-12: File added and changed by Sony Corporation

obj-$(CONFIG_NBX_EC_IPC) += ec_ipc_mod.o
ec_ipc_mod-objs          += ec_ipc.o ec_ipc_serial.o ec_suspend.o ec_ipc_bus.o
obj-$(CONFIG_NBX_EC_IPC) += ec_sysfs.o
obj-$(CONFIG_NBX_EC_IPC) += ec_ipc_acplug.o

obj-$(CONFIG_NBX_EC_IPC_LID_SWITCH) += ec_ipc_lidsw.o

obj-$(CONFIG_NBX_EC_TTY) += ec_tty.o
