#include/asm-arm/arch-avalanche/puma7/hw_mbox/Kbuild
#
# destination-y is the destination directory and is relative to ti/
# it must be defined and not blank! (if top level is required use destination-y := include/).
#
# header-y is a list of headers to be exported.
# header-y also indicates which subdirectories to visit (use trailing '/').
#
destination-y := include/
header-y += hw_mbox_defs.h
header-y += hw_mbox_drv.h
header-y += hw_mbox_mem_access.h
header-y += hw_mbox_socket.h
