#
# linux/drivers/spichips/Makefile
#
obj-$(CONFIG_MTD_SPI)		+= spimtd.o spiaccess.o spireg.o generic.o
obj-$(CONFIG_MTD_SPI_ST)   	+= m25pxx.o
obj-$(CONFIG_MTD_SPI_AT)   	+= atmel.o
obj-$(CONFIG_MTD_SPI_INTEL_S33) += intels33.o
obj-$(CONFIG_MTD_WPCM450_SPI)	+= hermon_spi.o
