#
# Makefile for the linux kernel.
#

obj-y	+= core.o irq.o time.o spearbasic.o  clock.o
#obj-$(CONFIG_SPEAR_LOCK)+= spr_hw_lock.o
obj-$(CONFIG_SPEAR_MISC_CONFIG)+= spr_misc_config.o
obj-y	+= hcl/
