# File: arch\arm\mach-avalanche\puma6\aep_drv/Makefile
#
# Makefile for the kernel aep device driver.
#



EXTRA_CFLAGS += -I$(srctree)/include/linux
EXTRA_CFLAGS += -I$(srctree)/include/asm-arm/arch-avalanche/generic
EXTRA_CFLAGS += -I$(srctree)/include/asm-arm/arch-avalanche/puma6
EXTRA_CFLAGS += -I$(srctree)/include/asm-arm/arch-avalanche/puma6/aep_drv

# for building object
obj-y := aep_core.o aep_gpio.o aep_iosfsb.o



