/*
 *
 *  Copyright (C)2008  ST MICROELECTRONICS
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * AUTHOR :  Deepak Sikri <deepak.sikri@st.com> */


#ifndef __SPEARBASIC_H
#define __SPEARBASIC_H

/*------------------------------------------------------------------------------
 External Reference Clock 0x3000_0FFF
------------------------------------------------------------------------------*/

/*========================================*/

#define SPEARBASIC_START_SDRAM					0x00000000


/* RAS */
#define SPEARBASIC_RAS1  (0x99000000)
#define SPEARBASIC_RAS2  (0x99000004)

/* ICM1 - Low speed connection */
#define SPEARBASIC_START_APB_UART0				0xD0000000
#define VA_SPEARBASIC_START_APB_UART0			IO_ADDRESS(SPEARBASIC_START_APB_UART0)
#define SPEARBASIC_SIZE_APB_UART0				0x00080000

#define SPEARBASIC_START_APB_UART1			SPEARBASIC_START_APB_UART0         
#define VA_SPEARBASIC_START_APB_UART1		VA_SPEARBASIC_START_APB_UART0
#define SPEARBASIC_SIZE_APB_UART1			SPEARBASIC_SIZE_APB_UART0            

#define SPEARBASIC_START_ICM1_ADC 				0xD0080000
#define VA_SPEARBASIC_START_ICM1_ADC 			IO_ADDRESS(SPEARBASIC_START_ICM1_ADC)
#define SPEARBASIC_SIZE_ICM1_ADC 				0x00080000

#define SPEARBASIC_START_SSP				0xD0100000
#define VA_SPEARBASIC_START_SSP				IO_ADDRESS(SPEARBASIC_START_SSP)
#define SPEARBASIC_SIZE_SSP					0x00080000


#define SPEARBASIC_START_I2C 					0xD0180000
#define VA_SPEARBASIC_START_I2C 				IO_ADDRESS(SPEARBASIC_START_I2C)
#define SPEARBASIC_SIZE_I2C 					0x00080000

#define SPEARBASIC_START_AHB_JPEG 				0xD0800000
#define VA_SPEARBASIC_START_AHB_JPEG 			IO_ADDRESS(SPEARBASIC_START_AHB_JPEG)
#define SPEARBASIC_SIZE_AHB_JPEG				0x00800000 

#define SPEARBASIC_START_IRDA					0xD1000000
#define VA_SPEARBASIC_START_IRDA				IO_ADDRESS(SPEARBASIC_START_IRDA)
#define SPEARBASIC_SIZE_IRDA					0x00080000

#define SPEARBASIC_START_NAND_FLASH_CTRLR		0x94000000
#define VA_SPEARBASIC_START_NAND_FLASH_CTRLR 	IO_ADDRESS(SPEARBASIC_START_NAND_FLASH_CTRLR)
#define SPEARBASIC_SIZE_NAND_FLASH_CTRLR		0x00800000


#define SPEARBASIC_START_NAND_FLASH_MEM		    0x80000000
#define VA_SPEARBASIC_START_NAND_FLASH_MEM   	IO_ADDRESS(0x80000000)
#define VA_SPEARBASIC_START_NAND_FLASH_CMD   	IO_ADDRESS(0x80010000)
#define VA_SPEARBASIC_START_NAND_FLASH_ADDR   	IO_ADDRESS(0x80020000)
//#define SPEARBASIC_SIZE_NAND_FLASH_MEM  		0x00800000
#define SPEARBASIC_SIZE_NAND_FLASH_MEM  		0x04000000


#define SPEARBASIC_START_SRAM					0xD2800000
#define VA_SPEARBASIC_START_SRAM				IO_ADDRESS(SPEARBASIC_START_SRAM)
#define SPEARBASIC_SIZE_SRAM					0x05800000


/* ICM2 - Application Subsystem */

//#define SPEARBASIC_START_ICM2_TMR0					0xD8000000
//#define VA_SPEARBASIC_START_ICM2_TMR0				IO_ADDRESS(0xD8000000)
//#define SPEARBASIC_SIZE_ICM2_TMR0					0x00080000

//#define SPEARBASIC_START_ICM2_TMR1					0xD8080000
//#define VA_SPEARBASIC_START_ICM2_TMR1				IO_ADDRESS(0xD8080000)
//#define SPEARBASIC_SIZE_ICM2_TMR1					0x00080000


#define SPEARBASIC_START_ICM2_ADC 					SPEARBASIC_START_ICM1_ADC
#define VA_SPEARBASIC_START_ICM2_ADC 				VA_SPEARBASIC_START_ICM1_ADC
#define SPEARBASIC_SIZE_ICM2_ADC 					SPEARBASIC_SIZE_ICM1_ADC

#define SPEARBASIC_START_HWACCEL_MOD0 				0xD8800000
#define VA_SPEARBASIC_START_HWACCEL_MOD0 			IO_ADDRESS(SPEARBASIC_START_HWACCEL_MOD0)
#define SPEARBASIC_SIZE_HWACCEL_MOD0 				0x00080000

#define SPEARBASIC_START_HWACCEL_MOD1 				0xD9000000
#define VA_SPEARBASIC_START_HWACCEL_MOD1 			IO_ADDRESS(SPEARBASIC_START_HWACCEL_MOD1)
#define SPEARBASIC_SIZE_HWACCEL_MOD1 				0x00080000

/* ICM4 - High Speed Connection */
#define SPEARBASIC_START_MAC						0xE0800000
#define VA_SPEARBASIC_START_MAC						IO_ADDRESS(SPEARBASIC_START_MAC)
#define SPEARBASIC_SIZE_MAC							0x00800000

#define SPEARBASIC_START_USBD_FIFO					0xE1000000
#define VA_SPEARBASIC_START_USBD_FIFO				IO_ADDRESS(SPEARBASIC_START_USBD_FIFO)
#define SPEARBASIC_SIZE_USBD_FIFO					0x00100000

#define SPEARBASIC_START_USBD_CFG 					0xE1100000
#define VA_SPEARBASIC_START_USBD_CFG 				IO_ADDRESS(SPEARBASIC_START_USBD_CFG)
#define SPEARBASIC_SIZE_USBD_CFG 					0x00100000

#define SPEARBASIC_START_USBD_PLUG					0xE1200000
#define VA_SPEARBASIC_START_USBD_PLUG				IO_ADDRESS(SPEARBASIC_START_USBD_PLUG)
#define SPEARBASIC_SIZE_USBD_PLUG					0x00100000

#define SPEARBASIC_START_USB_EHCI0_1				0xE1800000
#define VA_SPEARBASIC_START_USB_EHCI0_1				IO_ADDRESS(SPEARBASIC_START_USB_EHCI0_1)
#define SPEARBASIC_SIZE_USB_EHCI0_1					0x00100000

#define SPEARBASIC_START_USB_OHCI0					0xE1900000
#define VA_SPEARBASIC_START_USB_OHCI0				IO_ADDRESS(SPEARBASIC_START_USB_OHCI0)
#define SPEARBASIC_SIZE_USB_OHCI0					0x00100000


//#define SPEARBASIC_START_USB_EHCI1				0xE2000000
//#define VA_SPEARBASIC_START_USB_EHCI1				IO_ADDRESS(SPEARBASIC_START_USB_EHCI1)
//#define SPEARBASIC_SIZE_USB_EHCI1					0x00100000

#define SPEARBASIC_START_USB_OHCI1					0xE2100000
#define VA_SPEARBASIC_START_USB_OHCI1				IO_ADDRESS(SPEARBASIC_START_USB_OHCI1)
#define SPEARBASIC_SIZE_USB_OHCI1					0x00100000

#define SPEARBASIC_START_USB_ARB  					0xE2800000
#define VA_SPEARBASIC_START_USB_ARB  				IO_ADDRESS(SPEARBASIC_START_USB_ARB)
#define SPEARBASIC_SIZE_USB_ARB  					0x00010000


/* ML-1,2 -  Multi Layer CPU Subsystem */
#define SPEARBASIC_START_APB_GPT0					0xF0000000	
#define VA_SPEARBASIC_START_APB_GPT0				IO_ADDRESS(SPEARBASIC_START_APB_GPT0)
#define SPEARBASIC_SIZE_APB_GPT0					0x00100000

#define SPEARBASIC_START_VIC1						0xF1100000 
#define VA_SPEARBASIC_START_VIC1					IO_ADDRESS(SPEARBASIC_START_VIC1)
#define SPEARBASIC_SIZE_VIC1						0x00100000


/* ICM3 - Basic Subsystem */
#define SPEARBASIC_START_SFLASH_MEM				0xF8000000
#define VA_SPEARBASIC_START_SFLASH_MEM			IO_ADDRESS(SPEARBASIC_START_SFLASH_MEM)
#define SPEARBASIC_SIZE_SFLASH_MEM				0x04000000

#define SPEARBASIC_START_SFLASH_CTRL			0xFC000000 
#define VA_SPEARBASIC_START_SFLASH_CTRL			IO_ADDRESS(SPEARBASIC_START_SFLASH_CTRL)
#define SPEARBASIC_SIZE_SFALSH_CTRL				0x00200000

#define SPEARBASIC_START_CLCD_CTRL				0x60000000
#define VA_SPEARBASIC_START_CLCD_CTRL			IO_ADDRESS(SPEARBASIC_START_CLCD_CTRL)
#define SPEARBASIC_SIZE_CLCD_CTRL				0x00200000

#define SPEARBASIC_START_DMA		 			0xFC400000
#define VA_SPEARBASIC_START_DMA					IO_ADDRESS(SPEARBASIC_START_DMA)
#define SPEARBASIC_SIZE_DMA						0x00200000	

#define SPEARBASIC_START_SDRAM_CTRL				0xFC600000
#define VA_SPEARBASIC_START_SDRAM_CTRL			IO_ADDRESS(SPEARBASIC_START_SDRAM_CTRL)
#define SPEARBASIC_SIZE_SDRAM_CTRL				0x00200000

#define SPEARBASIC_START_BASIC_TMR 				0xFC800000
#define VA_SPEARBASIC_START_BASIC_TMR 			IO_ADDRESS(SPEARBASIC_START_BASIC_TMR)
#define SPEARBASIC_SIZE_BASIC_TMR 				0x00080000

#define SPEARBASIC_START_APB_WDT				0xFC880000
#define VA_SPEARBASIC_START_APB_WDT				IO_ADDRESS(SPEARBASIC_START_APB_WDT)
#define SPEARBASIC_SIZE_APB_WDT					0x00080000

#define SPEARBASIC_START_APB_RTC				0xFC900000
#define VA_SPEARBASIC_START_APB_RTC				IO_ADDRESS(SPEARBASIC_START_APB_RTC)
#define SPEARBASIC_SIZE_APB_RTC					0x00080000

#define SPEARBASIC_START_APB_GPIO0    			0xA9000000
#define VA_SPEARBASIC_START_APB_GPIO0  			IO_ADDRESS(SPEARBASIC_START_APB_GPIO0)
#define SPEARBASIC_SIZE_APB_GPIO0      			0x00080000

#define SPEARBASIC_START_APB_GPIO1    			0xFC980000
#define VA_SPEARBASIC_START_APB_GPIO1  			IO_ADDRESS(SPEARBASIC_START_APB_GPIO1)
#define SPEARBASIC_SIZE_APB_GPIO1      			0x00080000

#define SPEARBASIC_START_SYS_CTRL				0xFCA00000	
#define VA_SPEARBASIC_START_SYS_CTRL			IO_ADDRESS(SPEARBASIC_START_SYS_CTRL)
#define SPEARBASIC_SIZE_SYS_CTRL				0x00080000

#define SPEARBASIC_START_MISC_REG 				0xFCA80000 
#define VA_SPEARBASIC_START_MISC_REG 			IO_ADDRESS(SPEARBASIC_START_MISC_REG)
#define SPEARBASIC_SIZE_MISC_REG 				0x00080000	

#define SPEARBASIC_START_BASIC_TMR1 			0xFCB00000
#define VA_SPEARBASIC_START_BASIC_TMR1 			IO_ADDRESS(SPEARBASIC_START_BASIC_TMR1)
#define SPEARBASIC_SIZE_BASIC_TMR1 				0x00080000


/*========================================*/


#if 0
/*------------------------------------------------------------------------------
DMA MAC
------------------------------------------------------------------------------*/
#include "dmamac.h" 

/*------------------------------------------------------------------------------
 ST GENERAL CONFIGURATION REGISTERS
------------------------------------------------------------------------------*/
#include "gcfg.h" 

/*------------------------------------------------------------------------------
ST WATCHDOG TIMER
------------------------------------------------------------------------------*/
#include "wdt.h" 

/*------------------------------------------------------------------------------
ACCENT APB UART
------------------------------------------------------------------------------*/
#include "uart.h"
#endif 

#endif
