/* 
  This file is provided under a dual BSD/GPLv2 license.  When using or 
  redistributing this file, you may do so under either license.

  GPL LICENSE SUMMARY

  Copyright(c) 2017 Intel Corporation.

  This program is free software; you can redistribute it and/or modify 
  it under the terms of version 2 of the GNU General Public License as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
  General Public License for more details.

  You should have received a copy of the GNU General Public License 
  along with this program; if not, write to the Free Software 
  Foundation, Inc., 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
  The full GNU General Public License is included in this distribution 
  in the file called LICENSE.GPL.


  Contact Information:
  Intel Corporation
  2200 Mission College Blvd.
  Santa Clara, CA  97052

  BSD LICENSE 

  Copyright(c) 2017 Intel Corporation. All rights reserved.

  Redistribution and use in source and binary forms, with or without 
  modification, are permitted provided that the following conditions 
  are met:

    * Redistributions of source code must retain the above copyright 
      notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright 
      notice, this list of conditions and the following disclaimer in 
      the documentation and/or other materials provided with the 
      distribution.

    * Neither the name of Intel Corporation nor the names of its 
      contributors may be used to endorse or promote products derived 
      from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _PUMA7_PMU_H
#define _PUMA7_PMU_H

/**************************************************************************/
/** \enum   Puma7PmuSram_e 
/************************************************************************** 
 *  \brief  Puma7 Netip PMU SRAM Enumeration.
 *          
 **************************************************************************/
typedef enum _Puma7PmuSram_e 
{
    PMU_MOCA_MAC_SRAM_ID = 0,
    PMU_ARM11_SRAM_ID,
    PMU_PHY_DS1_CH1_SRAM_ID,
    PMU_PHY_DS1_CH2_SRAM_ID,
    PMU_PHY_DS1_CH3_SRAM_ID,
    PMU_PHY_DS1_CH4_SRAM_ID,
    PMU_PHY_DS1_CH5_SRAM_ID,
    PMU_PHY_DS1_CH6_SRAM_ID,
    PMU_PHY_DS1_CH7_SRAM_ID,
    PMU_PHY_DS1_CH8_SRAM_ID,
    PMU_PHY_DS1_CH9_SRAM_ID,
    PMU_PHY_DS1_CH10_SRAM_ID,
    PMU_PHY_DS1_CH11_SRAM_ID,
    PMU_PHY_DS1_CH12_SRAM_ID,
    PMU_PHY_DS1_MCR_SRAM_ID,
    PMU_PHY_DS2_CH1_SRAM_ID,
    PMU_PHY_DS2_CH2_SRAM_ID,
    PMU_PHY_DS2_CH3_SRAM_ID,
    PMU_PHY_DS2_CH4_SRAM_ID,
    PMU_PHY_DS2_CH5_SRAM_ID,
    PMU_PHY_DS2_CH6_SRAM_ID,
    PMU_PHY_DS2_CH7_SRAM_ID,
    PMU_PHY_DS2_CH8_SRAM_ID,
    PMU_PHY_DS2_CH9_SRAM_ID,
    PMU_PHY_DS2_CH10_SRAM_ID,
    PMU_PHY_DS2_CH11_SRAM_ID,
    PMU_PHY_DS2_CH12_SRAM_ID,
    PMU_PHY_DS2_MCR_SRAM_ID,
    PMU_PHY_DS3_CH1_SRAM_ID,
    PMU_PHY_DS3_CH2_SRAM_ID,
    PMU_PHY_DS3_CH3_SRAM_ID,
    PMU_PHY_DS3_CH4_SRAM_ID,
    PMU_PHY_DS3_CH5_SRAM_ID,
    PMU_PHY_DS3_CH6_SRAM_ID,
    PMU_PHY_DS3_CH7_SRAM_ID,
    PMU_PHY_DS3_CH8_SRAM_ID,
    PMU_PHY_DS3_MCR_SRAM_ID,
    PMU_PHY_US_CH1_SRAM_ID,
    PMU_PHY_US_CH2_SRAM_ID,
    PMU_PHY_US_CH3_SRAM_ID,
    PMU_PHY_US_CH4_SRAM_ID,
    PMU_PHY_US_CH5_SRAM_ID,
    PMU_PHY_US_CH6_SRAM_ID,
    PMU_PHY_US_CH7_SRAM_ID,
    PMU_PHY_US_CH8_SRAM_ID,
    PMU_PHY_US_MCR_SRAM_ID,
    PMU_OFDM_GLOBAL_SRAM_ID,
    PMU_OFDM_DEMOD0_CONF_SRAM_ID,
    PMU_OFDM_DEMOD0_OTHER_SRAM_ID,
    PMU_OFDM_DEMOD0_INTR_SRAM_ID,
    PMU_OFDM_DEMOD0_CMM_SRAM_ID,
    PMU_OFDM_DEMOD0_MPNE_SRAM_ID,
    PMU_OFDM_DEMOD1_CONF_SRAM_ID,
    PMU_OFDM_DEMOD1_OTHER_SRAM_ID,
    PMU_OFDM_DEMOD1_INTR_SRAM_ID,
    PMU_OFDM_DEMOD1_CMM_SRAM_ID,
    PMU_OFDM_DEMOD1_MPNE_SRAM_ID,
    PMU_OFDM_FEC0_CONF_SRAM_ID,
    PMU_OFDM_FEC0_NCP_SRAM_ID,
    PMU_OFDM_FEC0_OTHER_SRAM_ID,
    PMU_OFDM_FEC1_CONF_SRAM_ID,
    PMU_OFDM_FEC1_NCP_SRAM_ID,
    PMU_OFDM_FEC1_OTHER_SRAM_ID,
    PMU_OFDMA_US_CONF_TRANS_0_SRAM_ID,
    PMU_OFDMA_US_OTHER_TRANS_0_SRAM_ID,
    PMU_OFDMA_US_FRAMER_TRANS_0_SRAM_ID,
    PMU_OFDMA_US_CONF_TRANS_1_SRAM_ID,
    PMU_OFDMA_US_OTHER_TRANS_1_SRAM_ID,
    PMU_OFDMA_US_FRAMER_TRANS_1_SRAM_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_0_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_1_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_2_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_3_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_4_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_5_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_6_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_7_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_8_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_9_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_10_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_11_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_12_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_13_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_14_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_15_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_16_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_17_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_18_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_19_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_20_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_21_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_22_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_23_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_24_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_25_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_26_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_27_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_28_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_29_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_30_ID,
    PMU_DOCSIS_MAC_SRAM_HIGH_31_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_0_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_1_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_2_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_3_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_4_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_5_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_6_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_7_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_8_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_9_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_10_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_11_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_12_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_13_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_14_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_15_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_16_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_17_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_18_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_19_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_20_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_21_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_22_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_23_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_24_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_25_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_26_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_27_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_28_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_29_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_30_ID,
    PMU_DOCSIS_MAC_SRAM_LOW_31_ID,
    PMU_PP_ST1_SRAM_HIGH_0_ID,
    PMU_PP_ST1_SRAM_HIGH_1_ID,
    PMU_PP_ST1_SRAM_HIGH_2_ID,
    PMU_PP_ST1_SRAM_HIGH_3_ID,
    PMU_PP_ST1_SRAM_HIGH_4_ID,
    PMU_PP_ST1_SRAM_HIGH_5_ID,
    PMU_PP_ST1_SRAM_HIGH_6_ID,
    PMU_PP_ST1_SRAM_HIGH_7_ID,
    PMU_PP_ST1_SRAM_HIGH_8_ID,
    PMU_PP_ST1_SRAM_HIGH_9_ID,
    PMU_PP_ST1_SRAM_HIGH_10_ID,
    PMU_PP_ST1_SRAM_HIGH_11_ID,
    PMU_PP_ST1_SRAM_HIGH_12_ID,
    PMU_PP_ST1_SRAM_HIGH_13_ID,
    PMU_PP_ST1_SRAM_HIGH_14_ID,
    PMU_PP_ST1_SRAM_HIGH_15_ID,
    PMU_PP_ST1_SRAM_HIGH_16_ID,
    PMU_PP_ST1_SRAM_HIGH_17_ID,
    PMU_PP_ST1_SRAM_HIGH_18_ID,
    PMU_PP_ST1_SRAM_HIGH_19_ID,
    PMU_PP_ST1_SRAM_HIGH_20_ID,
    PMU_PP_ST1_SRAM_HIGH_21_ID,
    PMU_PP_ST1_SRAM_HIGH_22_ID,
    PMU_PP_ST1_SRAM_HIGH_23_ID,
    PMU_PP_ST1_SRAM_HIGH_24_ID,
    PMU_PP_ST1_SRAM_HIGH_25_ID,
    PMU_PP_ST1_SRAM_HIGH_26_ID,
    PMU_PP_ST1_SRAM_HIGH_27_ID,
    PMU_PP_ST1_SRAM_HIGH_28_ID,
    PMU_PP_ST1_SRAM_HIGH_29_ID,
    PMU_PP_ST1_SRAM_HIGH_30_ID,
    PMU_PP_ST1_SRAM_HIGH_31_ID,
    PMU_PP_ST1_SRAM_LOW_0_ID,
    PMU_PP_ST1_SRAM_LOW_1_ID,
    PMU_PP_ST1_SRAM_LOW_2_ID,
    PMU_PP_ST1_SRAM_LOW_3_ID,
    PMU_PP_ST1_SRAM_LOW_4_ID,
    PMU_PP_ST1_SRAM_LOW_5_ID,
    PMU_PP_ST1_SRAM_LOW_6_ID,
    PMU_PP_ST1_SRAM_LOW_7_ID,
    PMU_PP_ST1_SRAM_LOW_8_ID,
    PMU_PP_ST1_SRAM_LOW_9_ID,
    PMU_PP_ST1_SRAM_LOW_10_ID,
    PMU_PP_ST1_SRAM_LOW_11_ID,
    PMU_PP_ST1_SRAM_LOW_12_ID,
    PMU_PP_ST1_SRAM_LOW_13_ID,
    PMU_PP_ST1_SRAM_LOW_14_ID,
    PMU_PP_ST1_SRAM_LOW_15_ID,
    PMU_PP_ST1_SRAM_LOW_16_ID,
    PMU_PP_ST1_SRAM_LOW_17_ID,
    PMU_PP_ST1_SRAM_LOW_18_ID,
    PMU_PP_ST1_SRAM_LOW_19_ID,
    PMU_PP_ST1_SRAM_LOW_20_ID,
    PMU_PP_ST1_SRAM_LOW_21_ID,
    PMU_PP_ST1_SRAM_LOW_22_ID,
    PMU_PP_ST1_SRAM_LOW_23_ID,
    PMU_PP_ST1_SRAM_LOW_24_ID,
    PMU_PP_ST1_SRAM_LOW_25_ID,
    PMU_PP_ST1_SRAM_LOW_26_ID,
    PMU_PP_ST1_SRAM_LOW_27_ID,
    PMU_PP_ST1_SRAM_LOW_28_ID,
    PMU_PP_ST1_SRAM_LOW_29_ID,
    PMU_PP_ST1_SRAM_LOW_30_ID,
    PMU_PP_ST1_SRAM_LOW_31_ID,
    PMU_PP_ST2_SRAM_HIGH_0_ID,
    PMU_PP_ST2_SRAM_HIGH_1_ID,
    PMU_PP_ST2_SRAM_HIGH_2_ID,
    PMU_PP_ST2_SRAM_HIGH_3_ID,
    PMU_PP_ST2_SRAM_HIGH_4_ID,
    PMU_PP_ST2_SRAM_HIGH_5_ID,
    PMU_PP_ST2_SRAM_HIGH_6_ID,
    PMU_PP_ST2_SRAM_HIGH_7_ID,
    PMU_PP_ST2_SRAM_HIGH_8_ID,
    PMU_PP_ST2_SRAM_HIGH_9_ID,
    PMU_PP_ST2_SRAM_HIGH_10_ID,
    PMU_PP_ST2_SRAM_HIGH_11_ID,
    PMU_PP_ST2_SRAM_HIGH_12_ID,
    PMU_PP_ST2_SRAM_HIGH_13_ID,
    PMU_PP_ST2_SRAM_HIGH_14_ID,
    PMU_PP_ST2_SRAM_HIGH_15_ID,
    PMU_PP_ST2_SRAM_HIGH_16_ID,
    PMU_PP_ST2_SRAM_HIGH_17_ID,
    PMU_PP_ST2_SRAM_HIGH_18_ID,
    PMU_PP_ST2_SRAM_HIGH_19_ID,
    PMU_PP_ST2_SRAM_HIGH_20_ID,
    PMU_PP_ST2_SRAM_HIGH_21_ID,
    PMU_PP_ST2_SRAM_HIGH_22_ID,
    PMU_PP_ST2_SRAM_HIGH_23_ID,
    PMU_PP_ST2_SRAM_HIGH_24_ID,
    PMU_PP_ST2_SRAM_HIGH_25_ID,
    PMU_PP_ST2_SRAM_HIGH_26_ID,
    PMU_PP_ST2_SRAM_HIGH_27_ID,
    PMU_PP_ST2_SRAM_HIGH_28_ID,
    PMU_PP_ST2_SRAM_HIGH_29_ID,
    PMU_PP_ST2_SRAM_HIGH_30_ID,
    PMU_PP_ST2_SRAM_HIGH_31_ID,
    PMU_PP_ST2_SRAM_LOW_0_ID,
    PMU_PP_ST2_SRAM_LOW_1_ID,
    PMU_PP_ST2_SRAM_LOW_2_ID,
    PMU_PP_ST2_SRAM_LOW_3_ID,
    PMU_PP_ST2_SRAM_LOW_4_ID,
    PMU_PP_ST2_SRAM_LOW_5_ID,
    PMU_PP_ST2_SRAM_LOW_6_ID,
    PMU_PP_ST2_SRAM_LOW_7_ID,
    PMU_PP_ST2_SRAM_LOW_8_ID,
    PMU_PP_ST2_SRAM_LOW_9_ID,
    PMU_PP_ST2_SRAM_LOW_10_ID,
    PMU_PP_ST2_SRAM_LOW_11_ID,
    PMU_PP_ST2_SRAM_LOW_12_ID,
    PMU_PP_ST2_SRAM_LOW_13_ID,
    PMU_PP_ST2_SRAM_LOW_14_ID,
    PMU_PP_ST2_SRAM_LOW_15_ID,
    PMU_PP_ST2_SRAM_LOW_16_ID,
    PMU_PP_ST2_SRAM_LOW_17_ID,
    PMU_PP_ST2_SRAM_LOW_18_ID,
    PMU_PP_ST2_SRAM_LOW_19_ID,
    PMU_PP_ST2_SRAM_LOW_20_ID,
    PMU_PP_ST2_SRAM_LOW_21_ID,
    PMU_PP_ST2_SRAM_LOW_22_ID,
    PMU_PP_ST2_SRAM_LOW_23_ID,
    PMU_PP_ST2_SRAM_LOW_24_ID,
    PMU_PP_ST2_SRAM_LOW_25_ID,
    PMU_PP_ST2_SRAM_LOW_26_ID,
    PMU_PP_ST2_SRAM_LOW_27_ID,
    PMU_PP_ST2_SRAM_LOW_28_ID,
    PMU_PP_ST2_SRAM_LOW_29_ID,
    PMU_PP_ST2_SRAM_LOW_30_ID,
    PMU_PP_ST2_SRAM_LOW_31_ID,
    PMU_SRAM_MAX
} Puma7PmuSram_e;

#endif /* _PUMA7_PMU_H */


