#include/asm-arm/arch-avalanche/puma6/Kbuild
#
# destination-y is the destination directory and is relative to ti/
# it must be defined and not blank! (if top level is required use destination-y := include/).
#
# header-y is a list of headers to be exported.
# header-y also indicates which subdirectories to visit (use trailing '/').
#
destination-y := include/
header-y += docsis_ip_boot_params.h
header-y += puma6_cppi.h
header-y += puma6_cppi_prv.h
header-y += p_unit_api.h
header-y += iosfsb_drv/
