#include/asm-arm/arch-avalanche/generic/iosfsb_drv/Kbuild
#
# destination-y is the destination directory and is relative to ti/
# it must be defined and not blank! (if top level is required use destination-y := include/).
#
# header-y is a list of headers to be exported.
# header-y also indicates which subdirectories to visit (use trailing '/').
#
destination-y := include/asm-arm/arch-avalanche/puma7/iosfsb_drv/
header-y += iosfsb_api.h
