# File: arch\arm\mach-avalanche\ti_generic\time_capture\Makefile
#
# Makefile for the kernel time_capture device driver.
#


EXTRA_CFLAGS += -I$(srctree)/include/asm-arm/arch-avalanche/generic
EXTRA_CFLAGS += -I$(srctree)/include/linux
EXTRA_CFLAGS += -I$(srctree)/include/asm-arm/arch-avalanche/puma6

# for building object
obj-y := time_capture_drv.o





