# Copyright 2011-2012 Broadcom Corporation.  All rights reserved.
#
# Unless you and Broadcom execute a separate written software license
# agreement governing use of this software, this software is licensed to you
# under the terms of the GNU General Public License version 2, available at
# http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
#
# Notwithstanding the above, under no circumstances may you combine this
# software in any way with any other Broadcom software provided under a
# license other than the GPL, without Broadcom's express prior written
# consent.
#*****************************************************************************

obj-$(CONFIG_MACH_CAPRI_ROKU_AUSTIN) += board_roku_austin.o
CFLAGS_board_roku_austin.o += -Iarch/arm/mach-capri/custom_boards/hw_cfg/CAPRI_ROKU_AUSTIN \
-Iarch/arm/mach-capri/hw_cfg/CAPRI_RAY_NAND \
-Iarch/arm/mach-capri/hw_cfg/BASE \
-Idrivers/videocore/host_support/include
